In [1]:
import numpy as np
import pandas as pd

In [2]:
myindex=['kolar','bgl','mysore','bsk']
mydata=[100,200,300,400]

In [3]:
myser=pd.Series(data=myindex,index=mydata)
myser

100     kolar
200       bgl
300    mysore
400       bsk
dtype: object

In [4]:
myser1=pd.Series(myindex,index=mydata)
myser1

100     kolar
200       bgl
300    mysore
400       bsk
dtype: object

In [5]:
rand_data=np.random.randint(0,100,4)
rand_data

array([ 0, 73, 20, 51], dtype=int32)

In [6]:
names=['A','B','C','D']
ages=pd.Series(names,rand_data)
ages

0     A
73    B
20    C
51    D
dtype: object

In [7]:
ages=pd.Series(rand_data,names)
ages

A     0
B    73
C    20
D    51
dtype: int32

In [8]:
import pandas as pd
orders=pd.read_table('http://bit.ly//chiporders')
orders.head(2)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39

In [9]:
user_cols=['id','age','gender','work','salary']
movies=pd.read_table('http://bit.ly//movieusers',sep='|',header=None,names=user_cols)
movies.head()

   id  age gender        work salary
0   1   24      M  technician  85711
1   2   53      F       other  94043
2   3   23      M      writer  32067
3   4   24      M  technician  43537
4   5   33      F       other  15213

In [10]:
ufo=pd.read_table('http://bit.ly//uforeports',sep=',')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [11]:
ufo=pd.read_csv('http://bit.ly//uforeports')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [12]:
ufo[['City','Colors Reported','Time']].head()

                   City Colors Reported             Time
0                Ithaca             NaN   6/1/1930 22:00
1           Willingboro             NaN  6/30/1930 20:00
2               Holyoke             NaN  2/15/1931 14:00
3               Abilene             NaN   6/1/1931 13:00
4  New York Worlds Fair             NaN  4/18/1933 19:00

In [15]:
ufo1=ufo.City
type(ufo1)
ufo1.head()

0                  Ithaca
1             Willingboro
2                 Holyoke
3                 Abilene
4    New York Worlds Fair
Name: City, dtype: object

In [16]:
ufo1=ufo[['City']]
type(ufo1)
ufo1.head()

                   City
0                Ithaca
1           Willingboro
2               Holyoke
3               Abilene
4  New York Worlds Fair

In [17]:
ufo['location']=ufo.City+','+ufo.State
ufo.head()

,City,Colors Reported,Shape Reported,State,Time,location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca,NY"
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro,NJ"
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke,CO"
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene,KS"
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair,NY"

In [20]:
import pandas as pd
ufo=pd.read_csv('http://bit.ly//uforeports')
ufo['location'],ufo['timessss']=[ufo.City+'**'+ufo.State,ufo['Time']]

In [21]:
movies=pd.read_csv('http://bit.ly//imdbratings')
m1=movies[2:100]
m1

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
...,...,...,...,...,...,...
95,8.4,All About Eve,APPROVED,Drama,138,"[u'Bette Davis', u'Anne Baxter', u'George Sand..."
96,8.4,Yojimbo,UNRATED,Action,110,"[u'Toshir\xf4 Mifune', u'Eijir\xf4 T\xf4no', u..."
97,8.4,The Sting,PG,Comedy,129,"[u'Paul Newman', u'Robert Redford', u'Robert S..."
98,8.4,Rashomon,UNRATED,Crime,88,"[u'Toshir\xf4 Mifune', u'Machiko Ky\xf4', u'Ma..."
99,8.4,Amadeus,R,Biography,160,"[u'F. Murray Abraham', u'Tom Hulce', u'Elizabe..."

In [22]:
m1.describe()

       star_rating    duration
count     98.00000   98.000000
mean       8.54898  134.438776
std        0.16699   32.407542
min        8.40000   68.000000
25%        8.40000  110.500000
50%        8.50000  129.500000
75%        8.60000  154.750000
max        9.10000  229.000000

In [23]:
#movies.genre.describe()
movies[['genre']].describe()

        genre
count     979
unique     16
top     Drama
freq      278

In [24]:
movies.describe(include=['object'])

,title,content_rating,genre,actors_list
count,979,976,979,979
unique,975,12,16,969
top,Dracula,R,Drama,"[u'Daniel Radcliffe', u'Emma Watson', u'Rupert..."
freq,2,460,278,6

In [25]:
movies.shape

(979, 6)

In [26]:
ufo=pd.read_csv('http://bit.ly//uforeports')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [28]:
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time'], dtype='object')

In [29]:
ufo.rename(columns={'Colors Reported':'colors_reported','Time':'date_Time'},inplace=True)
ufo.head()

                   City colors_reported Shape Reported State        date_Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [33]:
ufo_cols=['cityzzz','colors','shapes','ssstate','datessss']
ufo.columns=ufo_cols
ufo.head()

                cityzzz colors    shapes ssstate         datessss
0                Ithaca    NaN  TRIANGLE      NY   6/1/1930 22:00
1           Willingboro    NaN     OTHER      NJ  6/30/1930 20:00
2               Holyoke    NaN      OVAL      CO  2/15/1931 14:00
3               Abilene    NaN      DISK      KS   6/1/1931 13:00
4  New York Worlds Fair    NaN     LIGHT      NY  4/18/1933 19:00

In [34]:
import pandas as pd
ufo=pd.read_csv('http://bit.ly//uforeports')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [36]:
ufo.drop('City',axis=1,inplace=True)
ufo.head()

  Colors Reported Shape Reported State             Time
0             NaN       TRIANGLE    NY   6/1/1930 22:00
1             NaN          OTHER    NJ  6/30/1930 20:00
2             NaN           OVAL    CO  2/15/1931 14:00
3             NaN           DISK    KS   6/1/1931 13:00
4             NaN          LIGHT    NY  4/18/1933 19:00

In [37]:
ufo.drop(['Colors Reported','State'],axis=1,inplace=True)
ufo.head()

  Shape Reported             Time
0       TRIANGLE   6/1/1930 22:00
1          OTHER  6/30/1930 20:00
2           OVAL  2/15/1931 14:00
3           DISK   6/1/1931 13:00
4          LIGHT  4/18/1933 19:00

In [38]:
ufo.drop([0,1],axis=0,inplace=True)
ufo.head()

  Shape Reported             Time
2           OVAL  2/15/1931 14:00
3           DISK   6/1/1931 13:00
4          LIGHT  4/18/1933 19:00
5           DISK  9/15/1934 15:30
6         CIRCLE   6/15/1935 0:00

In [39]:
movies=pd.read_csv('http://bit.ly//imdbratings')
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [40]:
movies.title.sort_values().head(20)

542            (500) Days of Summer
5                      12 Angry Men
201                12 Years a Slave
698                       127 Hours
110           2001: A Space Odyssey
910                            2046
596                        21 Grams
624                       25th Hour
708                28 Days Later...
60                         3 Idiots
225                          3-Iron
570                             300
555                    3:10 to Yuma
427    4 Months, 3 Weeks and 2 Days
824                              42
597                           50/50
203                           8 1/2
170                A Beautiful Mind
941                A Bridge Too Far
571                    A Bronx Tale
Name: title, dtype: object

In [41]:
movies.title.sort_values(ascending=False).head()

864               [Rec]
526                Zulu
615          Zombieland
677              Zodiac
955    Zero Dark Thirty
Name: title, dtype: object

In [42]:
movies.sort_values('title',ascending=False).head()

,star_rating,title,content_rating,genre,duration,actors_list
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
526,7.8,Zulu,UNRATED,Drama,138,"[u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac..."
615,7.7,Zombieland,R,Comedy,88,"[u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."

In [43]:
movies.sort_values(['duration','star_rating'],ascending=False).head()

,star_rating,title,content_rating,genre,duration,actors_list
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."

In [44]:
movies=pd.read_csv('http://bit.ly//imdbratings')
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [45]:
movies.shape

(979, 6)

In [46]:
booleans=[]
for length in movies.duration:
    if length>=200:
        booleans.append(True)
    else:
        booleans.append(False)

In [47]:
len(booleans)

979

In [48]:
booleans[0:10]

[False, False, True, False, False, False, False, True, False, False]

In [49]:
ser=pd.Series(booleans)
ser.head()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [50]:
movies[ser].head()

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."

In [51]:
ser=movies.duration>=200
movies[ser].head()

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."

In [52]:
movies[movies.duration>=200].head()

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."

In [53]:
m1=movies[movies.duration>200].genre
pd.DataFrame(m1)

         genre
7    Adventure
17       Drama
78       Crime
85   Adventure
142  Adventure
157      Drama
204  Adventure
445  Adventure
476      Drama
630  Biography
767     Action

In [55]:
movies[(movies.duration>=200)&(movies.genre=='Drama')]

,star_rating,title,content_rating,genre,duration,actors_list
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."

In [56]:
movies[(movies.genre=='Crime')|(movies.genre=='Drama')|(movies.genre=='Action')].head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [57]:
movies[movies.genre.isin(['Crime','Drama','Action'])].head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [58]:
drinks=pd.read_csv('http://bit.ly//drinksbycountry')
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [61]:
drinks.mean(numeric_only=True)

beer_servings                   106.160622
spirit_servings                  80.994819
wine_servings                    49.450777
total_litres_of_pure_alcohol      4.717098
dtype: float64

In [62]:
drinks['beer_servings'].mean()

np.float64(106.16062176165804)

In [64]:
drinks.mean(axis=1,numeric_only=True).head()

0      0.000
1     69.975
2      9.925
3    176.850
4     81.225
dtype: float64

In [66]:
drinks.mean(axis='columns',numeric_only=True).head()

0      0.000
1     69.975
2      9.925
3    176.850
4     81.225
dtype: float64

In [68]:
drinks.mean(axis='rows',numeric_only=True).head()

beer_servings                   106.160622
spirit_servings                  80.994819
wine_servings                    49.450777
total_litres_of_pure_alcohol      4.717098
dtype: float64

In [69]:
drinks.mean(axis='index',numeric_only=True).head()

beer_servings                   106.160622
spirit_servings                  80.994819
wine_servings                    49.450777
total_litres_of_pure_alcohol      4.717098
dtype: float64

In [70]:
drinks.dtypes

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [71]:
drinks['beer_servings']=drinks.beer_servings.astype(float)
drinks.dtypes

country                          object
beer_servings                   float64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [72]:
drinks[drinks.continent=='Africa'].beer_servings.mean()

np.float64(61.471698113207545)

In [74]:
drinks[drinks.continent=='Africa'].mean(axis=0,numeric_only=True)

beer_servings                   61.471698
spirit_servings                 16.339623
wine_servings                   16.264151
total_litres_of_pure_alcohol     3.007547
dtype: float64

In [76]:
drinks.groupby('continent').beer_servings.mean()

continent
Africa            61.471698
Asia              37.045455
Europe           193.777778
North America    145.434783
Oceania           89.687500
South America    175.083333
Name: beer_servings, dtype: float64

In [77]:
drinks.groupby('continent').beer_servings.describe()

,count,mean,std,min,25%,50%,75%,max
continent,,,,,,,,
Africa,53.0,61.471698,80.557816,0.0,15.00,32.0,76.00,376.0
Asia,44.0,37.045455,49.469725,0.0,4.25,17.5,60.50,247.0
Europe,45.0,193.777778,99.631569,0.0,127.00,219.0,270.00,361.0
North America,23.0,145.434783,79.621163,1.0,80.00,143.0,198.00,285.0
Oceania,16.0,89.687500,96.641412,0.0,21.00,52.5,125.75,306.0
South America,12.0,175.083333,65.242845,93.0,129.50,162.5,198.00,333.0

In [78]:
drinks.groupby('continent').beer_servings.agg(['count','max','min'])

               count    max   min
continent
Africa            53  376.0   0.0
Asia              44  247.0   0.0
Europe            45  361.0   0.0
North America     23  285.0   1.0
Oceania           16  306.0   0.0
South America     12  333.0  93.0

In [79]:
import numpy as np
import pandas as pd

In [80]:
data_one={'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']}
data_two={'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']}
one=pd.DataFrame(data_one)
two=pd.DataFrame(data_two)

In [81]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [82]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [90]:
axis0=pd.concat([one,two],axis=0)
axis0

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [91]:
axis1=pd.concat([one,two],axis=1)
axis1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [93]:
two.columns=one.columns

In [94]:
two.columns

Index(['A', 'B'], dtype='object')

In [95]:
two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [98]:
pd.concat([one,two],axis=0)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [99]:
registrations=pd.DataFrame({'reg_id':[1,2,3,4],'name':['abc','def','lmn','xyz']})
logins=pd.DataFrame({'log_id':[1,2,3,4],'name':['123','abc','789','xyz']})

In [100]:
registrations

   reg_id name
0       1  abc
1       2  def
2       3  lmn
3       4  xyz

In [101]:
logins

   log_id name
0       1  123
1       2  abc
2       3  789
3       4  xyz

In [102]:
pd.merge(registrations,logins,how='inner',on='name')

   reg_id name  log_id
0       1  abc       2
1       4  xyz       4

In [103]:
pd.merge(registrations,logins,how='inner')

   reg_id name  log_id
0       1  abc       2
1       4  xyz       4

In [104]:
pd.merge(registrations,logins,how='left')

   reg_id name  log_id
0       1  abc     2.0
1       2  def     NaN
2       3  lmn     NaN
3       4  xyz     4.0

In [105]:
pd.merge(registrations,logins,how='right')

   reg_id name  log_id
0     NaN  123       1
1     1.0  abc       2
2     NaN  789       3
3     4.0  xyz       4

In [107]:
pd.merge(registrations,logins,how='outer')

   reg_id name  log_id
0     NaN  123     1.0
1     NaN  789     3.0
2     1.0  abc     2.0
3     2.0  def     NaN
4     3.0  lmn     NaN
5     4.0  xyz     4.0

In [108]:
import pandas as pd
ufo=pd.read_csv('http://bit.ly//uforeports')
#ufo['location'],ufo['timessss']=[ufo.city+'**'+ufo.State,ufo['Time']]

In [109]:
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [110]:
ufo['Location'],ufo['timessss']=[ufo.City+'**'+ufo.State,ufo['Time']]

In [111]:
ufo.head()

,City,Colors Reported,Shape Reported,State,Time,Location,timessss
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca**NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro**NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke**CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene**KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair**NY,4/18/1933 19:00

In [112]:
ufo=pd.read_csv('http://bit.ly//uforeports')
ufo.tail()

              City Colors Reported Shape Reported State              Time
18236   Grant Park             NaN       TRIANGLE    IL  12/31/2000 23:00
18237  Spirit Lake             NaN           DISK    IA  12/31/2000 23:00
18238  Eagle River             NaN            NaN    WI  12/31/2000 23:45
18239  Eagle River             RED          LIGHT    WI  12/31/2000 23:45
18240         Ybor             NaN           OVAL    FL  12/31/2000 23:59

In [113]:
ufo.isnull().tail()

        City  Colors Reported  Shape Reported  State   Time
18236  False             True           False  False  False
18237  False             True           False  False  False
18238  False             True            True  False  False
18239  False            False           False  False  False
18240  False             True           False  False  False

In [114]:
ufo.notnull().tail()

       City  Colors Reported  Shape Reported  State  Time
18236  True            False            True   True  True
18237  True            False            True   True  True
18238  True            False           False   True  True
18239  True             True            True   True  True
18240  True            False            True   True  True

In [115]:
ufo.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [116]:
ufo.shape

(18241, 5)

In [117]:
ufo.dropna(how='any').shape

(2486, 5)

In [118]:
ufo.dropna(how='all').shape

(18241, 5)

In [119]:
ufo.dropna(subset=['City','Shape Reported'],how='all').shape

(18237, 5)

In [120]:
ufo['Shape Reported'].value_counts(dropna=False).head()

Shape Reported
LIGHT       2803
NaN         2644
DISK        2122
TRIANGLE    1889
OTHER       1402
Name: count, dtype: int64

In [122]:
ufo['Shape Reported'].fillna(value='Besant',inplace=True)
ufo['Shape Reported'].value_counts().head()

Shape Reported
LIGHT       2803
Besant      2644
DISK        2122
TRIANGLE    1889
OTHER       1402
Name: count, dtype: int64

In [123]:
orders=pd.read_table('http://bit.ly/chiporders')
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [124]:
orders.item_name.str.upper().head()

0             CHIPS AND FRESH TOMATO SALSA
1                                     IZZE
2                         NANTUCKET NECTAR
3    CHIPS AND TOMATILLO-GREEN CHILI SALSA
4                             CHICKEN BOWL
Name: item_name, dtype: object

In [126]:
orders.item_name.str.contains('Chicken').head()

0    False
1    False
2    False
3    False
4     True
Name: item_name, dtype: bool

In [128]:
orders[orders.item_name.str.contains('Chicken')].head()

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25

In [129]:
orders.choice_description.str.replace('[','').str.replace(']','').head()

0                                                  NaN
1                                           Clementine
2                                                Apple
3                                                  NaN
4    Tomatillo-Red Chili Salsa (Hot), Black Beans, ...
Name: choice_description, dtype: object